development:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
  options:
    raise_not_found_error: false

test:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
  options:
    raise_not_found_error: false

production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
  options:
    raise_not_found_error: false
